# -*- coding: utf-8 -*-
"""Relevamiento de oportunidades para fotógrafa / maquilladora social.
Zona Norte GBA + CABA lindante. Relevado el 22/08/2026."""

FECHA = "22/08/2026"

# categoría, perfil, entidad, puesto, zona, detalle, contacto, cómo postularse, link
AVISOS = [
 ("Aviso concreto", "Fotografía", "ALTHI SRL",
  "Fotógrafo/a profesional",
  "Martínez (San Isidro)",
  "Sesiones de foto producto, lifestyle y/o moda. Piden experiencia comprobable, creatividad y responsabilidad en la entrega del material.",
  "oficina.empleo@vicentelopez.gov.ar · +54 9 11 3003-3113 · Hilarión de la Quintana 2168, Olivos",
  "Postulación online en el Portal de Empleo de Vicente López (registro gratuito). Si el aviso venció, consultar por mail o teléfono a la Oficina de Empleo por búsquedas equivalentes.",
  "https://empleo.vicentelopez.gov.ar/oferta-de-empleo/11976-althi-srl-fotografo-profesional"),

 ("Aviso concreto", "Ambos", "Empresa de accesorios de fiesta y vestidos (vía Jobrapido)",
  "Maquilladora + Peinadora + Fotógrafo para sesión de fotos",
  "Palermo / Belgrano, CABA",
  "EL MÁS RELEVANTE: una misma producción busca maquilladora Y fotógrafo. Producción de fotos para catálogo de vestidos y accesorios de fiesta.",
  "Sin teléfono público en el agregador",
  "Postularse desde el listado de Jobrapido buscando el aviso «Maquilladora, Peinadora, Fotógrafo para Sesión de». Requiere registro gratuito.",
  "https://ar.jobrapido.com/Ofertas-de-trabajo-para-Maquilladora-en-Argentina"),

 ("Aviso concreto", "Fotografía", "Helohim Pitrelli",
  "Se necesita fotógrafa para restaurantes de Capital Federal",
  "CABA + Zona Norte",
  "Sacar y vender fotos en restaurantes de Capital Federal y Zona Norte. Cámara réflex o celular de alta definición. Martes a domingos de 19:30 a 00:00 hs; sábados, domingos y feriados desde las 12:30 hs.",
  "Sin teléfono público en el aviso",
  "Postulación por Bumeran (cuenta gratuita).",
  "https://www.bumeran.com.ar/empleos/se-necesita-fotografa-para-restaurantes-de-capital-federal-helohim-pitrelli-1116519557.html"),

 ("Aviso concreto", "Fotografía", "Helohim Pitrelli",
  "Fotógrafa freelance con cámara réflex para restaurantes",
  "CABA + GBA",
  "Freelance. Sacar y vender fotos en restaurantes. Se valora experiencia en fotografía gastronómica. Pago por jornada.",
  "Sin teléfono público en el aviso",
  "Postulación por Bumeran.",
  "https://www.bumeran.com.ar/empleos/se-necesita-fotografa-free-lance-con-camara-digital-reflex-para-sacar-y-vender-fotos-en-restaurantes-helohim-pitrelli-1116711225.html"),

 ("Aviso concreto", "Fotografía", "Helohim Pitrelli",
  "Fotógrafo freelance",
  "CABA + GBA",
  "Freelance, esquema fotógrafo-vendedor en restaurantes.",
  "Sin teléfono público en el aviso",
  "Postulación por Bumeran.",
  "https://www.bumeran.com.ar/empleos/fotografo-freelance-helohim-pitrelli-1116726611.html"),

 ("Aviso concreto", "Fotografía", "Helohim Pitrelli",
  "Fotógrafa freelance",
  "CABA + GBA",
  "Freelance, esquema fotógrafo-vendedor en restaurantes.",
  "Sin teléfono público en el aviso",
  "Postulación por Bumeran.",
  "https://www.bumeran.com.ar/empleos/fotografa-freelance-helohim-pitrelli-1118031978.html"),

 ("Aviso concreto", "Fotografía", "Helohim Pitrelli — PERFIL DE EMPRESA",
  "Todas sus búsquedas activas",
  "CABA + Zona Norte + GBA",
  "Publica avisos de fotografía de forma recurrente y va rotando zonas (Zona Norte, San Miguel, Villa del Parque, Los Polvorines, Ezeiza). Conviene seguir el perfil y revisarlo cada semana. Sueldos informados en avisos similares: $35.000 a $45.000 por jornada, o alrededor de $195.000 semanales.",
  "Sin teléfono público",
  "Seguir el perfil en Bumeran y postularse a cada aviso nuevo.",
  "https://www.bumeran.com.ar/perfiles/empresa_helohim-pitrelli_13286558.html"),

 ("Aviso concreto", "Maquillaje", "Local de artículos de belleza, maquillaje y uñas (vía Computrabajo)",
  "Maquillador/a profesional con experiencia en Make Up",
  "Belgrano, CABA (limita con Vicente López)",
  "Jornada completa, presencial. Maquillaje social y artístico. Se valoran conocimientos de dermocosmética y diagnóstico de piel. Piden buena dicción y perfil de atención al cliente.",
  "Sin teléfono público en el aviso",
  "Postulación por Computrabajo (cuenta gratuita). Enviar CV con pretensiones salariales.",
  "https://ar.computrabajo.com/ofertas-de-trabajo/oferta-de-trabajo-de-maquilladora-profesional-con-experiencia-en-make-up-caba-en-belgrano-60366350f5ba3a3761373e686dcf3405"),

 ("Aviso concreto", "Fotografía", "Fabricante de repuestos de motocross (nombre no publicado en el agregador)",
  "Diseño gráfico + fotografía",
  "Zona Norte — Ruta 197 y Panamericana (Pacheco / Tigre)",
  "Empleado/a joven con conocimientos de diseño gráfico y fotografía, orientado a diseño de página web y publicaciones. Ubicación muy conveniente para Zona Norte.",
  "Sin teléfono público en el agregador",
  "Buscar el aviso por título en Jooble o Computrabajo y postularse por la plataforma.",
  "https://ar.jooble.org/trabajo-fot%C3%B3grafo/Buenos-Aires"),

 ("Aviso concreto", "Fotografía", "Empresa gastronómica y de show (nombre no publicado)",
  "Fotógrafo/a de eventos + venta de producto",
  "CABA",
  "Eventos a diario. Piden buena presencia, experiencia en la tarea, perfil comercial y de venta, e inglés intermedio para atender turismo internacional.",
  "Sin teléfono público en el agregador",
  "Postulación por Jooble o Bumeran.",
  "https://ar.jooble.org/trabajo-fotografo-eventos/Buenos-Aires"),

 ("Aviso concreto", "Fotografía", "App FiestÓN",
  "Fotógrafo/a de eventos",
  "Buenos Aires",
  "Fotografiar a los invitados durante eventos con un dispositivo que sube las fotos directo a la app FiestÓN. Formato ideal para fotografía social.",
  "Sin teléfono público en el agregador",
  "Postulación por Jooble.",
  "https://ar.jooble.org/trabajo-fot%C3%B3grafo/Argentina"),

 ("Aviso concreto", "Maquillaje", "Grupo del sector belleza / cosmética / dermocosmética (nombre no publicado)",
  "Encargado/a de local — dermocosmética",
  "Zona Norte (Unicenter, Martínez)",
  "Grupo reconocido del rubro belleza busca líder o encargada para un local en Zona Norte. Piden formación en dermocosmética, cosmetología o cosmiatría; se valora perfil de maquilladora. Asesoramiento, venta y activaciones.",
  "Sin teléfono público en el agregador",
  "Postulación por Bumeran, área Estética y Cuidado Personal.",
  "https://www.bumeran.com.ar/en-buenos-aires/empleos-area-oficios-y-otros-subarea-estetica-y-cuidado-personal.html"),

 ("Aviso concreto", "Fotografía", "Institución (nombre no publicado)",
  "Fotógrafo/a corporativo",
  "Buenos Aires",
  "Fotógrafo con experiencia en corporaciones, enfocado en comunicación de identidad, valores e imagen corporativa.",
  "Sin teléfono público en el agregador",
  "Postulación por Jooble o LinkedIn.",
  "https://ar.linkedin.com/jobs/fotografia-empleos"),

 ("Aviso concreto", "Fotografía", "Clínica odontológica (nombre no publicado)",
  "Fotógrafo/a",
  "Recoleta, CABA",
  "Perfil proactivo, con ganas de aprender y trabajo en equipo. Fotografía clínica y documentación de tratamientos.",
  "Sin teléfono público en el agregador",
  "Postulación por Jooble o Jobsora.",
  "https://ar.jobsora.com/empleos-fot%C3%B3grafo-buenos-aires"),

 ("Aviso concreto", "Fotografía", "Conectan2",
  "Fotógrafo/a — Buenos Aires",
  "Buenos Aires",
  "Sesiones en estudio, exteriores y eventos. Uso de equipo profesional y software de edición, gestión del flujo de trabajo y entrega al cliente. Ofrecen salario competitivo y crecimiento.",
  "Formulario de postulación en el sitio",
  "Postulación desde la ficha del aviso en Conectan2.",
  "https://conectan2.com/empleo/fotografo-buenos-aires-argentina/"),

 ("Aviso concreto", "Fotografía", "Aviso «FOTOGRAFA/O» (Bumeran)",
  "Fotógrafa/o",
  "Buenos Aires",
  "Aviso abierto de fotografía publicado en Bumeran.",
  "Sin teléfono público en el aviso",
  "Postulación por Bumeran.",
  "https://www.bumeran.com.ar/empleos/fotografa-o-2151265.html"),
]

OFICINAS = [
 ("Oficina de Empleo", "Ambos", "Oficina de Empleo — Municipio de Vicente López",
  "Intermediación laboral + portal de empleo",
  "Olivos / Vicente López / Florida",
  "Portal municipal gratuito que conecta vecinos con empresas de la zona. Acá está publicado el aviso de ALTHI SRL. Tiene filtros por sector (Diseño, Comunicación y Marketing) y por localidad.",
  "oficina.empleo@vicentelopez.gov.ar · +54 9 11 3003-3113 · Hilarión de la Quintana 2168, Olivos",
  "Registrarse en el portal y cargar el CV. Además, escribir o llamar para que la incorporen a la base de intermediación laboral.",
  "https://empleo.vicentelopez.gov.ar/"),

 ("Oficina de Empleo", "Ambos", "Portal de Empleo — Municipio de San Isidro",
  "Portal de empleo + Trabajo y Producción",
  "San Isidro, Martínez, Beccar, Boulogne, Villa Adelina",
  "Plataforma gratuita con filtros por tipo de jornada (full time, part time, freelance, temporario). Los comercios de San Isidro publican vacantes gratis, por eso aparecen búsquedas chicas (peluquerías, estudios, salones) que no llegan a Computrabajo.",
  "siempleos@sanisidro.gov.ar · trabajoyproduccion@sanisidro.gob.ar · WhatsApp (11) 3585-0997",
  "Registrarse en el portal. También conviene escribir al WhatsApp presentando el perfil doble: fotógrafa + maquilladora social.",
  "https://www.sanisidro.gob.ar/portal-de-empleo"),

 ("Oficina de Empleo", "Ambos", "Empleo y Comercio San Isidro",
  "Bolsa de trabajo de comercios locales",
  "San Isidro",
  "Portal complementario donde publican directamente los comercios del partido.",
  "siempleos@sanisidro.gov.ar",
  "Registro y postulación online.",
  "https://empleoycomercio.sanisidro.gob.ar/"),

 ("Oficina de Empleo", "Ambos", "Portal de Empleo — Municipio de Tigre",
  "Intermediación laboral",
  "Tigre, Troncos del Talar, Pacheco, Benavídez, Nordelta, Rincón",
  "Equipo de intermediación laboral que resuelve búsquedas de comercios y empresas del distrito. Publican búsquedas nuevas todas las semanas. IMPORTANTE: el servicio es sólo para personas con domicilio en Tigre en el DNI.",
  "empleos@tigre.gob.ar · 5282-7565 / 5282-7564 · Lisandro de la Torre 2500, Troncos del Talar",
  "Registrarse en el portal y completar el perfil con estudios y experiencia; después los contactan para entrevista.",
  "https://empleos.tigre.gob.ar/"),

 ("Oficina de Empleo", "Ambos", "Oficina de Empleo — Municipio de San Fernando",
  "Empleo y Capacitación Laboral",
  "San Fernando, Virreyes, Victoria",
  "Programas de incentivo laboral, capacitaciones y articulación con empresas locales. Atención de lunes a viernes de 8 a 13 y de 14 a 17 hs.",
  "(011) 4580-5734",
  "Llamar o acercarse a dejar el CV en la oficina.",
  "https://www.sanfernando.gob.ar/municipio/secretarias/secretaria-de-desarrollo-social-educacion-y-medio-ambiente/educacion-integracion/empleo"),

 ("Oficina de Empleo", "Ambos", "Portal de Empleo — Municipio de Escobar",
  "Bolsa de trabajo municipal",
  "Escobar, Belén de Escobar, Garín, Maquinista Savio",
  "Portal de búsquedas del municipio (plataforma Zoho Recruit). Escobar tiene mucho movimiento de eventos y salones de fiesta.",
  "Alta online en el portal",
  "Registrarse en el portal de carreras y postularse a las búsquedas abiertas.",
  "https://escobar.zohorecruit.com/careers"),

 ("Oficina de Empleo", "Ambos", "Empleo — Municipio de Pilar",
  "Oficina de empleo municipal",
  "Pilar, Del Viso, Manzanares, Villa Rosa",
  "Atención de lunes a viernes de 8 a 15 hs. Zona con alta densidad de salones de fiesta y quintas de eventos.",
  "Plataforma de consultas y turnos en el sitio",
  "Sacar turno online y presentar el CV.",
  "https://pilar.gov.ar/comunidad/empleo/"),
]

BUSQUEDAS = [
 ("Computrabajo", "Fotografía", "Fotógrafa — Buenos Aires GBA", "https://ar.computrabajo.com/trabajo-de-fotografa-en-buenos-aires-gba"),
 ("Computrabajo", "Fotografía", "Fotógrafo — Buenos Aires GBA", "https://ar.computrabajo.com/trabajo-de-fotografo-en-buenos-aires-gba"),
 ("Computrabajo", "Maquillaje", "Maquilladora — Argentina", "https://ar.computrabajo.com/trabajo-de-maquilladora"),
 ("Computrabajo", "Ambos", "Todos los empleos en San Isidro", "https://ar.computrabajo.com/empleos-en-buenos-aires-gba-en-san-isidro"),
 ("Computrabajo", "Ambos", "Todos los empleos en Belgrano (CABA)", "https://ar.computrabajo.com/empleos-en-capital-federal-en-belgrano"),
 ("Bumeran", "Ambos", "Búsqueda «zona norte» en San Isidro", "https://www.bumeran.com.ar/en-buenos-aires/san-isidro/empleos-busqueda-zona-norte.html"),
 ("Bumeran", "Maquillaje", "Área Estética y Cuidado Personal — Buenos Aires", "https://www.bumeran.com.ar/en-buenos-aires/empleos-area-oficios-y-otros-subarea-estetica-y-cuidado-personal.html"),
 ("Bumeran", "Ambos", "Empleos en Tigre", "https://www.bumeran.com.ar/en-buenos-aires/tigre/empleos.html"),
 ("Bumeran", "Ambos", "Empleos en Benavídez", "https://www.bumeran.com.ar/en-buenos-aires/benavidez/empleos.html"),
 ("Bumeran", "Ambos", "Empleos publicados hoy — Buenos Aires", "https://www.bumeran.com.ar/en-buenos-aires/empleos-publicacion-hoy.html"),
 ("ZonaJobs", "Ambos", "Empleos en Tigre", "https://www.zonajobs.com.ar/en-buenos-aires/tigre/empleos.html"),
 ("Jooble", "Maquillaje", "Maquillaje / maquilladora — Buenos Aires", "https://ar.jooble.org/trabajo-maquillaje-maquilladora/Buenos-Aires"),
 ("Jooble", "Fotografía", "Fotógrafo — Buenos Aires", "https://ar.jooble.org/trabajo-fot%C3%B3grafo/Buenos-Aires"),
 ("Jooble", "Fotografía", "Fotógrafo de eventos — Buenos Aires", "https://ar.jooble.org/trabajo-fotografo-eventos/Buenos-Aires"),
 ("Jooble", "Fotografía", "Fotógrafo de moda — Buenos Aires", "https://ar.jooble.org/trabajo-fotografo-moda/Buenos-Aires"),
 ("Jooble", "Fotografía", "Asistente de estudio fotográfico — Buenos Aires", "https://ar.jooble.org/trabajo-asistente-estudio-fotografico/Buenos-Aires"),
 ("Indeed", "Maquillaje", "Maquillaje — Buenos Aires", "https://ar.indeed.com/q-maquillaje-l-buenos-aires,-buenos-aires-empleos.html"),
 ("Indeed", "Maquillaje", "Maquilladora — Buenos Aires", "https://ar.indeed.com/q-maquilladora-l-buenos-aires,-buenos-aires-empleos.html"),
 ("Indeed", "Fotografía", "Fotógrafo — Argentina", "https://ar.indeed.com/q-fotografo-empleos.html"),
 ("Indeed", "Fotografía", "Fotógrafa — Argentina", "https://ar.indeed.com/q-fotografa-empleos.html"),
 ("Indeed", "Ambos", "Todos los empleos en San Isidro", "https://ar.indeed.com/l-san-isidro,-buenos-aires-empleos.html"),
 ("Indeed", "Ambos", "Part time en Vicente López", "https://ar.indeed.com/q-empleo-part-time-l-vicente-l%C3%B3pez,-buenos-aires-empleos.html"),
 ("LinkedIn", "Fotografía", "Empleos de Fotografía — Argentina", "https://ar.linkedin.com/jobs/fotografia-empleos"),
 ("LinkedIn", "Fotografía", "Empleos de Fotógrafo — Argentina", "https://ar.linkedin.com/jobs/fot%C3%B3grafo-empleos"),
 ("Jobsora", "Maquillaje", "Maquillaje — Buenos Aires", "https://ar.jobsora.com/empleos-maquillaje-buenos-aires"),
 ("Jobsora", "Fotografía", "Fotógrafo — Buenos Aires", "https://ar.jobsora.com/empleos-fot%C3%B3grafo-buenos-aires"),
 ("Jobted", "Fotografía", "Fotógrafo — Buenos Aires", "https://www.jobted.com.ar/trabajo-fot%C3%B3grafo-en-buenos-aires"),
 ("Jobted", "Maquillaje", "Maquilladora — Argentina", "https://www.jobted.com.ar/trabajo-maquilladora"),
 ("Jobrapido", "Maquillaje", "Maquilladora — Argentina", "https://ar.jobrapido.com/Ofertas-de-trabajo-para-Maquilladora-en-Argentina"),
 ("Trabajos Diarios", "Fotografía", "Avisos de fotografía", "https://ar.trabajosdiarios.com/ofertas-trabajo/de-fotografia"),
 ("Mitula Empleo", "Maquillaje", "Maquilladora — Buenos Aires", "https://empleo.mitula.com.ar/empleo/maquilladora-buenos-aires"),
 ("Mitula Empleo", "Fotografía", "Fotógrafo — Buenos Aires", "https://empleo.mitula.com.ar/empleo/fotografo-buenos-aires"),
 ("Acción Trabajo", "Ambos", "Empleos de Zona Norte", "https://ar.acciontrabajo.com/empleos-de-zona-norte"),
 ("Acción Trabajo", "Fotografía", "Empleos de fotografía", "https://ar.acciontrabajo.com/empleos-de-fotografia"),
 ("Trovit", "Fotografía", "Fotógrafo — Capital Federal", "https://empleo.trovitargentina.com.ar/trabajo-fotografo-en-capital-federal,-capital-federal"),
 ("Opcionempleo", "Maquillaje", "Maquilladora — Buenos Aires", "https://www.opcionempleo.com.ar/empleo-maquilladora/buenos-aires-222552.html"),
 ("Talent.com", "Fotografía", "Fotógrafo — Argentina", "https://ar.talent.com/jobs?k=fot%C3%B3grafo&l="),
 ("Glassdoor", "Fotografía", "Fotógrafo — Argentina", "https://www.glassdoor.com.ar/Empleo/fotografo-empleos-SRCH_KO0,9.htm"),
]

CANALES = [
 ("Bolsa del rubro belleza", "Maquillaje", "Peluquería al Día — Ofertas laborales",
  "Zona Norte / CABA / GBA",
  "LA MEJOR FUENTE PARA MAQUILLAJE: es el único tablero donde cada aviso publica el mail o el WhatsApp directo de quien contrata. Los avisos arrancan con «OFERTA LABORAL» e incluyen lugar de trabajo y contacto. Ya hay avisos de peluquerías-spa de Núñez y centros de estética.",
  "Cada aviso trae su propio mail o WhatsApp",
  "Revisar la sección dos o tres veces por semana y escribir directo al contacto del aviso. Además, publicar su propio perfil en la sección «Busco trabajo».",
  "http://www.peluqueriaaldia.com/ofertas-laborales/"),

 ("Bolsa del rubro belleza", "Maquillaje", "Peluquería al Día — Bolsa de trabajo / Busco trabajo",
  "Zona Norte / CABA / GBA",
  "Sección para publicar el propio perfil y que la contacten los salones directamente.",
  "Publicación propia en el sitio",
  "Publicar aviso con el perfil: maquilladora social, zona norte, disponibilidad horaria.",
  "https://www.peluqueriaaldia.com/bolsa-de-trabajo-peluqueria-phpzonaid4op1/"),

 ("Instagram", "Ambos", "@empleos.zonanorte",
  "Tigre, Escobar y alrededores",
  "Cuenta de bolsa de trabajo específica de Zona Norte. Publica changas y búsquedas chicas que no llegan a los portales grandes.",
  "DM de Instagram",
  "Seguir la cuenta, activar notificaciones y responder por mensaje directo.",
  "https://www.instagram.com/empleos.zonanorte/"),

 ("Grupo de Facebook", "Ambos", "Empleos Zona Norte: Tigre — San Fernando — San Isidro",
  "Tigre, San Fernando, San Isidro",
  "Grupo activo donde comercios y emprendedores publican búsquedas con teléfono o WhatsApp directo.",
  "Los avisos incluyen teléfono o WhatsApp de quien publica",
  "Pedir ingreso al grupo, activar notificaciones y publicar un aviso de presentación con portfolio.",
  "https://www.facebook.com/groups/736114356522788/"),

 ("Grupo de Facebook", "Ambos", "TRABAJOS EN ZONA NORTE — BUENOS AIRES",
  "Zona Norte GBA",
  "Grupo de avisos laborales de la zona.",
  "Los avisos incluyen contacto directo",
  "Pedir ingreso y publicar presentación.",
  "https://www.facebook.com/groups/316586916903622/"),

 ("Grupo de Facebook", "Ambos", "BOLSA DE TRABAJO ZONA NORTE",
  "Zona Norte GBA",
  "Grupo de avisos laborales de la zona.",
  "Los avisos incluyen contacto directo",
  "Pedir ingreso y publicar presentación.",
  "https://www.facebook.com/groups/1528246167427681/"),

 ("Grupo de Facebook", "Ambos", "Empleos Zona Norte",
  "Zona Norte GBA",
  "Grupo de avisos laborales de la zona.",
  "Los avisos incluyen contacto directo",
  "Pedir ingreso y publicar presentación.",
  "https://www.facebook.com/groups/991303545429937/"),

 ("Grupo de Facebook", "Fotografía", "Posteo: «Busco fotógrafo por zona norte de fotoproducto»",
  "Zona Norte GBA",
  "Pedido concreto publicado en un grupo: buscan fotógrafo de foto producto en Zona Norte. Se responde por comentario o mensaje directo al autor del posteo.",
  "Comentario o DM al autor del posteo",
  "Entrar al posteo, comentar y mandar DM con portfolio.",
  "https://www.facebook.com/groups/26660720821/posts/busco-fot%C3%B3grafo-por-zona-norte-de-fotoproducto/10162197079285822/"),

 ("Marketplace de servicios", "Maquillaje", "MercadoLibre Servicios — Maquilladoras y peinadoras Zona Norte",
  "Zona Norte GBA",
  "Categoría activa de maquilladoras y peinadoras en Zona Norte. Sirve para publicar el servicio y captar demanda directa, y para ver quién está trabajando la zona.",
  "Mensajería de MercadoLibre",
  "Publicar el servicio (gratis) y responder consultas.",
  "https://servicios.mercadolibre.com.ar/belleza-cuidado-personal/maquilladoras-peinadoras/maquilladora-y-peinadora-zona-norte"),

 ("Directorio de bodas", "Maquillaje", "Casamientos Online — Maquillaje y Peinados Buenos Aires",
  "Buenos Aires / Zona Norte",
  "Directorio líder de proveedores de casamientos desde 1999. Los estudios grandes que figuran ahí suman maquilladoras colaboradoras para temporada alta: conviene escribirles una por una ofreciendo colaboración.",
  "Cada proveedor publica su teléfono y mail en su ficha",
  "Dar de alta el perfil propio y, en paralelo, contactar a los estudios ya listados para trabajar como colaboradora.",
  "https://www.casamientosonline.com/buenos-aires/proveedor/maquillaje-y-peinados_CO_r12"),

 ("Directorio de bodas", "Fotografía", "Casamientos Online — Foto y Video Buenos Aires",
  "Buenos Aires / Zona Norte",
  "Mismo criterio: los estudios de foto y video de casamientos contratan segundos fotógrafos y asistentes para la temporada. Cada ficha tiene teléfono y mail.",
  "Cada proveedor publica su teléfono y mail en su ficha",
  "Contactar estudios de la zona ofreciendo disponibilidad como segunda fotógrafa.",
  "http://www.casamientosonline.com/buenos-aires/proveedor/foto-y-video_CO_r8"),

 ("Salones y eventos", "Ambos", "Salones para fiestas en San Isidro (EnZonaNorte)",
  "San Isidro",
  "Listado de salones del partido con datos de contacto. Los salones derivan proveedores de foto y maquillaje a sus clientes: conviene presentarse para quedar en su lista de recomendados.",
  "Cada salón publica teléfono y dirección",
  "Llamar o mandar mail presentando servicios de foto + maquillaje para quinces y casamientos.",
  "https://www.enzonanorte.com/rubro/Salones-para-Fiestas/San-Isidro/837/10/1"),

 ("Salones y eventos", "Ambos", "Salones de eventos en Tigre",
  "Tigre",
  "Listado de salones de eventos del partido con contacto.",
  "Cada salón publica teléfono y dirección",
  "Presentarse como proveedora para su lista de recomendados.",
  "https://salonesdeeventos.com.ar/salones-en-tigre.php"),

 ("Salones y eventos", "Ambos", "Salones de eventos en San Isidro",
  "San Isidro",
  "Listado de salones de eventos del partido con contacto.",
  "Cada salón publica teléfono y dirección",
  "Presentarse como proveedora para su lista de recomendados.",
  "http://www.salonesdeeventos.com.ar/salones-en-san-isidro.php"),

 ("Estudio fotográfico", "Fotografía", "CKS Photo Studio",
  "San Isidro",
  "Estudio de alquiler en San Isidro. Los estudios de alquiler suelen derivar producción y necesitar fotógrafos y maquilladoras para las sesiones que se alquilan.",
  "Contacto publicado en el sitio del estudio",
  "Escribir ofreciendo servicios como fotógrafa y maquilladora para las producciones que alquilan el espacio.",
  "https://www.cksphotostudio.com.ar/"),
]
